services:
  youtube-genai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GENAI_SCOPE=local_prod
    volumes:
      - .:/app