services:
  youtube-genai:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GENAI_SCOPE=local_prod
      - OLLAMA_HOST=http://ollama:11434  # URL del servicio Ollama dentro de la red

    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - ollama  # Asegura que Ollama se inicie antes de este servicio

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"  # Puerto expuesto para Ollama
    volumes:
      - ollama:/root/.ollama  # Volumen persistente para los datos de Ollama
    networks:
      - app-network  # Conecta este servicio a la red compartida

networks:
  app-network:
    driver: bridge

volumes:
  ollama: